### ISSUE TITLE
Application Error on Heroku

### ISSUE THREAD

**Issue by sahil-lakhwani** [amirrajan/word-finder#9]
I get this log when I start the app on Heroku. It is attempting to start as 'node server.js', may be this is the problem because this app is to be started as 'node start.js'

2016-08-12T12:59:44.254844+00:00 heroku[web.1]: Starting process with command `node server.js`
2016-08-12T12:59:46.131163+00:00 app[web.1]:
2016-08-12T12:59:46.131164+00:00 app[web.1]: SyntaxError: Unexpected token import
2016-08-12T12:59:46.131161+00:00 app[web.1]: (function (exports, require, module, __filename, __dirname) { import express from 'express';
2016-08-12T12:59:46.131162+00:00 app[web.1]:                                                               ^^^^^^
2016-08-12T12:59:46.131146+00:00 app[web.1]: /app/server.js:1
2016-08-12T12:59:46.180972+00:00 heroku[web.1]: Process exited with status 1
2016-08-12T12:59:46.131169+00:00 app[web.1]:     at node.js:405:3
2016-08-12T12:59:46.131164+00:00 app[web.1]:     at exports.runInThisContext (vm.js:53:16)
2016-08-12T12:59:46.131165+00:00 app[web.1]:     at Module._compile (module.js:387:25)
2016-08-12T12:59:46.131166+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-08-12T12:59:46.131166+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-08-12T12:59:46.131167+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-08-12T12:59:46.131168+00:00 app[web.1]:     at Function.Module.runMain (module.js:447:10)
2016-08-12T12:59:46.131168+00:00 app[web.1]:     at startup (node.js:148:18)
2016-08-12T12:59:46.186491+00:00 heroku[web.1]: State changed from crashed to starting
2016-08-12T12:59:46.185444+00:00 heroku[web.1]: State changed from starting to crashed
2016-08-12T12:59:47.837373+00:00 heroku[web.1]: Starting process with command `node server.js`

**Comment by amirrajan** [comment]
Try `node start.js`, I probably need to update the Procfile and packages.json. Let me know if that fixes it.
